FROM swaggerapi/swagger-codegen-cli-v3:3.0.25 as builder

WORKDIR /mock-server-code
COPY ./openapi.yml ./
RUN java -jar /opt/swagger-codegen-cli/swagger-codegen-cli.jar \
  generate -i openapi.yml -l nodejs-server -o ./

FROM node:14.16.0-alpine3.13 as executor
COPY docker-entrypoint.sh /usr/local/bin/
RUN chmod 744 /usr/local/bin/docker-entrypoint.sh
ENV READY_DIR=/ready_mock
WORKDIR $READY_DIR
COPY --from=builder /mock-server-code/ ./

WORKDIR /app
ENTRYPOINT ["docker-entrypoint.sh"]
